version: 1

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logger/info.txt
    encoding: utf8

  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: simple
    filename: logger/error.txt
    encoding: utf8

loggers:
  my_logger:
    level: INFO
    handlers: [info_file_handler, error_file_handler]
    propagate: no

root:
  level: INFO
  handlers: [info_file_handler, error_file_handler]
